name: SpellCheck

on:
  pull_request:
    types:
      # default
      - opened
      - synchronize
      - reopened
      # re-run if base branch is changed, since previous merge commit may generate incorrect diff
      - edited

permissions:
  contents: read

jobs:
  spellcheck:
    name: SpellCheck (${{ matrix.os }}, ${{ matrix.index }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-slim]
        index: [1]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
          sparse-checkout: |
            .github
            eng
            specification/servicefabricmanagedclusters

      - name: Run spelling check
        run: |
          ./eng/common/scripts/check-spelling-in-changed-files.ps1 `
              -CSpellConfigPath 'cspell.json' `
              -SourceCommittish HEAD `
              -TargetCommittish HEAD^ `
              -SpellCheckRoot (Resolve-Path specification) `
              -ExitWithError
          if ($LASTEXITCODE) {
            Write-Host "Spelling errors found in changed files. See https://aka.ms/ci-fix#spell-check"
            exit $LASTEXITCODE
          }
        shell: pwsh

      - name: Print file list
        if: always()
        run: cat /tmp/files.txt

      - name: run cspell from bash
        if: always()
        run: cat /tmp/files.txt | npm --prefix /tmp/cspell-tool-path exec --no -- cspell lint --config cspell.json --no-must-find-files --root /home/runner/work/azure-rest-api-specs/azure-rest-api-specs/specification --file-list stdin
