name: Swagger LintDiff

on: pull_request

permissions:
  contents: read

jobs:
  typespec-validation:
    name: TypeSpec Validation
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
